#!/usr/bin/env python3
import argparse
import getpass
import platform
import sys
import subprocess
from os.path import expanduser
from urllib.parse import quote

parser = argparse.ArgumentParser()
parser.add_argument('domains', help='domains to mount', nargs='*')
args = parser.parse_args()

if len(args.domains) == 0:
    print('Must list at least one network storage server')
    exit(1)

#password = quote(getpass.getpass())

drives = ['fouo', 'exportcont', 'other']

my_os = platform.platform()

mnt_cmd = ['mount', '-t']

if my_os.startswith('Darwin') or my_os.startswith('macOS-12'):
    mnt_cmd.append('smbfs')
elif my_os.startswith('Linux'):
    mnt_cmd.append('cifs')
else:
    print('Unknown os: ', my_os)
    sys.exit(1)

for serv in args.domains:
    for d in drives:
        print('Mounting {} from {}'.format(d, serv))
        d_args = ['//{}.kitware.com/{}'.format(serv,d),
                  expanduser('~/network/{}/{}'.format(serv,d))]
        #print(' '.join(mnt_cmd + d_args))
        subprocess.call(mnt_cmd + d_args)

